version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: ai_trend_postgres
    restart: always
    environment:
      POSTGRES_DB: trend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  qdrant:
    image: qdrant/qdrant:v1.9.0
    container_name: ai_trend_qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  app:
    build: .
    container_name: ai_trend_app
    depends_on:
      - postgres
      - qdrant
    env_file: .env
    volumes:
      - .:/app
    command: ["python", "src/main.py"]